name: cached_s5_manager
description: A cache manager for cached_s5 libraries.
repository:
homepage:
version: 0.0.1

environment:
  sdk: ^3.4.4

dependencies:
  path: ^1.9.0
  path_provider: ^2.1.4
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

topics:
  - cache
  - s5
